// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectService.API.Infrastructure.Context;

#nullable disable

namespace ProjectService.API.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectService.API.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Unspecified).AddTicks(7049), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description 1",
                            EndDate = new DateTime(2024, 11, 9, 8, 25, 26, 213, DateTimeKind.Local).AddTicks(7037),
                            Name = "Project 1",
                            StartDate = new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Local).AddTicks(7018),
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Unspecified).AddTicks(7051), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Unspecified).AddTicks(7058), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description 2",
                            EndDate = new DateTime(2024, 11, 9, 8, 25, 26, 213, DateTimeKind.Local).AddTicks(7057),
                            Name = "Project 2",
                            StartDate = new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Local).AddTicks(7057),
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Unspecified).AddTicks(7059), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Unspecified).AddTicks(7061), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Description 3",
                            EndDate = new DateTime(2024, 11, 9, 8, 25, 26, 213, DateTimeKind.Local).AddTicks(7060),
                            Name = "Project 3",
                            StartDate = new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Local).AddTicks(7060),
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 10, 30, 8, 25, 26, 213, DateTimeKind.Unspecified).AddTicks(7061), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "user3"
                        });
                });

            modelBuilder.Entity("ProjectService.API.Domain.Entities.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#",
                            UserId = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ASP.NET",
                            UserId = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Entity Framework",
                            UserId = "user2"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Azure",
                            UserId = "user2"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blazor",
                            UserId = "user3"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Microservices",
                            UserId = "user3"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Docker",
                            UserId = "user4"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kubernetes",
                            UserId = "user4"
                        },
                        new
                        {
                            Id = 9,
                            Name = "DevOps",
                            UserId = "user5"
                        },
                        new
                        {
                            Id = 10,
                            Name = "CI/CD",
                            UserId = "user5"
                        });
                });

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTag");
                });

            modelBuilder.Entity("ProjectTags", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTags");
                });

            modelBuilder.Entity("ProjectTag", b =>
                {
                    b.HasOne("ProjectService.API.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectService.API.Domain.Entities.Tags", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTags", b =>
                {
                    b.HasOne("ProjectService.API.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectService.API.Domain.Entities.Tags", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
